name: Eyan Aly

on:
  push:
    branches: [ main ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Greetings
        run: echo Hello From Apun

      - name: Check Syntax Error
        run: python -m py_compile file.py
