name: Eyan Aly

on:
  push:
   branches: [ main ]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
     - name: Greetings
       run: echo "Hello From Apun"

     - name: Check Python Syntax
        run: python -m compileall -q .
